services:
  mysql:
    image: mysql
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: scholarspheredb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5001:5001"
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
      - /backend/node_modules
    environment:
      - DATABASE_URL="mysql://root:12345678@mysql:3306/scholarspheredb"
  
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - /frontend/node_modules

volumes:
  mysql-data:

